variable "application_name" {}
variable "region" {}
variable "vpc_cidr" {}
variable "pub_sub_cidr" {}
variable "pub_sub_cidr1" {}
variable "pri_sub_cidr" {}
variable "ami_id" {}
variable "instance_type" {}
variable "cluster_name" {}
variable "node_instance_type" {}